/** @type {import('tailwindcss').Config} */
import daisyui from 'daisyui';
import { themes } from './scripts/design-tokens.mjs';

export default {
  content: ['./src/**/*.html', './src/**/*.ts', './dist/**/*.html'],
  theme: {
    extend: {
      fontFamily: {
        brand: ['Sigmar One', 'Red Hat Text', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        sans: [
          'Red Hat Text',
          'Inter',
          'ui-sans-serif',
          'system-ui',
          'Segoe UI',
          'Helvetica Neue',
          'Arial',
          'Noto Sans',
          'Liberation Sans',
          'sans-serif',
        ],
        mono: [
          'JetBrains Mono',
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          'Liberation Mono',
          'Courier New',
          'monospace',
        ],
      },
      fontSize: {
        '2xs': '0.65rem',
      },
    },
  },
  // Allow daisyUI preflight (keeps most resets minimal); if conflict arises revert.
  corePlugins: {},
  plugins: [daisyui],
  daisyui: {
    themes: [
      {
        gistlight: {
          ...require('daisyui/src/theming/themes')['[data-theme=light]'],
          primary: themes.light.primary,
          'primary-focus': themes.light.primaryHover,
          'primary-content': themes.light.primaryFg,
          secondary: themes.light.secondary,
          'secondary-focus': themes.light.secondaryHover,
          'secondary-content': themes.light.secondaryFg,
          accent: themes.light.accent,
          'accent-focus': themes.light.accentHover,
          'accent-content': themes.light.accentFg,
          neutral: themes.light.neutral,
          'neutral-content': themes.light.neutralFg,
          info: themes.light.info,
          success: themes.light.success,
          warning: themes.light.warning,
          error: themes.light.error,
          '--rounded-btn': '0.375rem',
        },
      },
      {
        gistalt: {
          ...require('daisyui/src/theming/themes')['[data-theme=light]'],
          primary: themes.alt.primary,
          'primary-focus': themes.alt.primaryHover,
          'primary-content': themes.alt.primaryFg,
          secondary: themes.alt.secondary,
          'secondary-focus': themes.alt.secondaryHover,
          'secondary-content': themes.alt.secondaryFg,
          accent: themes.alt.accent,
          'accent-focus': themes.alt.accentHover,
          'accent-content': themes.alt.accentFg,
          neutral: themes.alt.neutral,
          'neutral-content': themes.alt.neutralFg,
          info: themes.alt.info,
          success: themes.alt.success,
          warning: themes.alt.warning,
          error: themes.alt.error,
          '--rounded-btn': '0.375rem',
        },
      },
      {
        gistdark: {
          ...require('daisyui/src/theming/themes')['[data-theme=dark]'],
          primary: themes.dark.primary,
          'primary-focus': themes.dark.primaryHover,
          'primary-content': themes.dark.primaryFg,
          secondary: themes.dark.secondary,
          'secondary-focus': themes.dark.secondaryHover,
          'secondary-content': themes.dark.secondaryFg,
          accent: themes.dark.accent,
          'accent-focus': themes.dark.accentHover,
          'accent-content': themes.dark.accentFg,
          neutral: themes.dark.neutral,
          'neutral-content': themes.dark.neutralFg,
          info: themes.dark.info,
          success: themes.dark.success,
          warning: themes.dark.warning,
          error: themes.dark.error,
          '--rounded-btn': '0.375rem',
        },
      },
    ],
    darkTheme: 'gistdark',
    logs: false,
  },
};
